### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Skyfay** [hypherionmc/sdlink#133]
Hey, 

I installed the mod on the server but the server won't start. I guess its a problem with luckperms. I disabled luckperms usage in `simple-discord-compat.toml` but that changed nothing. 

Minecraft 1.21.1 Fabric 0.16.9.

```
09:50:31
Failed to start the minecraft server
Console09:50:31
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'sdlink' at 'com.hypherionmc.sdlink.loaders.fabric.SDLinkFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: com/hypherionmc/craterlib/api/events/compat/LuckPermsCompatEvents$GroupRemovedEvent
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?]
	at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?]
	at knot/com.hypherionmc.craterlib.core.event.CraterEventBus.getEventMethodsOf(CraterEventBus.java:61) ~[CraterLib-Fabric-1.21-2.1.1.jar:?]
	at knot/com.hypherionmc.craterlib.core.event.CraterEventBus.registerEventListener(CraterEventBus.java:35) ~[CraterLib-Fabric-1.21-2.1.1.jar:?]
	at knot/com.hypherionmc.sdlink.loaders.fabric.SDLinkFabric.onInitializeServer(SDLinkFabric.java:30) ~[SimpleDiscordLink-Universal-3.2.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.hypherionmc.craterlib.api.events.compat.LuckPermsCompatEvents$GroupRemovedEvent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?]
	at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?]
	at knot/com.hypherionmc.craterlib.core.event.CraterEventBus.getEventMethodsOf(CraterEventBus.java:61) ~[CraterLib-Fabric-1.21-2.1.1.jar:?]
	at knot/com.hypherionmc.craterlib.core.event.CraterEventBus.registerEventListener(CraterEventBus.java:35) ~[CraterLib-Fabric-1.21-2.1.1.jar:?]
	at knot/com.hypherionmc.sdlink.loaders.fabric.SDLinkFabric.onInitializeServer(SDLinkFabric.java:30) ~[SimpleDiscordLink-Universal-3.2.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more
JDA MainWS-ReadThread/INFO09:50:31
Connected to WebSocket
Finished Loading!
pool-7-thread-2/INFO09:50:31
Successfully connected to discord
```

**Comment by hypherionmc** [comment]
Hey. 

`Caused by: java.lang.NoClassDefFoundError: com/hypherionmc/craterlib/api/events/compat/LuckPermsCompatEvents$GroupRemovedEvent` 

Update CraterLib to 2.1.2 :)

**Comment by Skyfay** [comment]
Works. Thanks :)

**Comment by Skyfay** [comment]
> Update CraterLib to 2.1.2 :)

Another question. I think the docs are outdated? If I follow the documentation, this is what i create.
But i get an error on server start and the config looks not the same as in the example from:
https://sdlink.fdd-docs.com/features/luckperms-sync/ 

```toml
#LuckPerms group syncing
[luckperms]
	#Sync Groups/Ranks to Minecraft from Discord Roles
	syncToMinecraft = true
	#Sync Groups/Ranks to Discord roles from Minecraft
	syncToDiscord = true
	#List of Ranks and Roles that will be synced. Check the wiki on how to configure this
	syncs = [
        rank = "default"
        role = "1313798888905379880"
        rank = "1"
        role = "1313799179616649216"
        rank = "2"
        role = "1313800921364299827"
        rank = "3"
        role = "1313800987122864169"
        rank = "4"
        role = "1313801051673071741"
        ]
```

It should look like that, then it works:
```toml
#LuckPerms group syncing
[luckperms]
	#Sync Groups/Ranks to Minecraft from Discord Roles
	syncToMinecraft = true
	#Sync Groups/Ranks to Discord roles from Minecraft
	syncToDiscord = true
	#List of Ranks and Roles that will be synced. Check the wiki on how to configure this
    syncs = [
    { rank = "default", role = "1313798888905379880" },
    { rank = "1", role = "1313799179616649216" },
    { rank = "2", role = "1313800921364299827" },
    { rank = "3", role = "1313800987122864169" },
    { rank = "4", role = "1313801051673071741" }
]
```

**Comment by hypherionmc** [comment]
The docs is correct, as it's new for this feature.

```toml
#LuckPerms group syncing
[luckperms]
    #Sync Groups/Ranks to Minecraft from Discord Roles
    syncToMinecraft = true
    #Sync Groups/Ranks to Discord roles from Minecraft
    syncToDiscord = true
    #List of Ranks and Roles that will be synced. Check the wiki on how to configure this
    [[luckperms.syncs]]
        rank = "testing"
        role = "1310640194755493969"
```

So yours should look like this:

```toml
#LuckPerms group syncing
[luckperms]
	#Sync Groups/Ranks to Minecraft from Discord Roles
	syncToMinecraft = true
	#Sync Groups/Ranks to Discord roles from Minecraft
	syncToDiscord = true
	#List of Ranks and Roles that will be synced. Check the wiki on how to configure this
        [[luckperms.syncs]]
            rank = "default"
            role = "1313798888905379880"
        [[luckperms.syncs]]
            rank = "1"
            role = "1313799179616649216"
        [[luckperms.syncs]]
            rank = "2"
            role = "1313800921364299827"
```

etc. You duplicate the whole `[[luckperms.syncs]]` block each time

I didn't have time to do the videos on these features yet. Should be soon

**Comment by hypherionmc** [comment]
> It should look like that, then it works:

Huh. Didn't know toml supports using json to specify table lists. That's kinda cool

**Comment by Skyfay** [comment]
> So yours should look like this:

Okay, because the default config on the server looks like this:
```toml
#LuckPerms group syncing
[luckperms]
	#Sync Groups/Ranks to Minecraft from Discord Roles
	syncToMinecraft = true
	#Sync Groups/Ranks to Discord roles from Minecraft
	syncToDiscord = true
	#List of Ranks and Roles that will be synced. Check the wiki on how to configure this
    syncs = []
```
The docs use like `[[luckperms.syncs]]` this was a bit confusing haha


> Huh. Didn't know toml supports using json to specify table lists. That's kinda cool

It should work, the server starting as expected. I will test if the sync works as expected :)

**Comment by hypherionmc** [comment]
> Okay, because the default config on the server looks like this:

Yeah. The default config doesn't contain any entries, so it just puts an empty array for the value there. That's why we include both the empty config, and the example with changes after so you can see the difference :)

**Comment by EpyonProjects** [comment]
I'm sure a multi line example in a block comment would be helpful for others.  I don't know toml format and have never seen a syntax like that.  (I'm here because I couldn't figure it out and went searching)

**Comment by Skyfay** [comment]
> ```toml
> #LuckPerms group syncing
> [luckperms]
> 	#Sync Groups/Ranks to Minecraft from Discord Roles
> 	syncToMinecraft = true
> 	#Sync Groups/Ranks to Discord roles from Minecraft
> 	syncToDiscord = true
> 	#List of Ranks and Roles that will be synced. Check the wiki on how to configure this
>     syncs = [
>     { rank = "default", role = "1313798888905379880" },
>     { rank = "1", role = "1313799179616649216" },
>     { rank = "2", role = "1313800921364299827" },
>     { rank = "3", role = "1313800987122864169" },
>     { rank = "4", role = "1313801051673071741" }
> ]
> ```

I have just tested it. Works perfectly :)

**Comment by hypherionmc** [comment]
Closing this out for now, as the original issue was just CraterLib being outdated. 

If there are any more issues, please feel free to reopen
