### ISSUE TITLE
Crash on server startup when using with Dimensional Ascension server

### ISSUE THREAD

**Issue by Un1q32** [hypherionmc/sdlink#137]
Using the latest (0.8.1) Dimensional Ascension server files + dynmap 3.7 beta 4 for 1.19.2

```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: java.lang.IncompatibleClassChangeError: class shadows.placebo.color.GradientColor cannot inherit from final class net.minecraft.network.chat.TextColor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.enchantment.Enchantments.<clinit>(Enchantments.java:15)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.m_205977_(Registry.java:199)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.lambda$internalRegister$54(Registry.java:461)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.lambda$static$70(Registry.java:667)
	at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:666)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:110)
	... 13 more
```

**Comment by hypherionmc** [comment]
`Caused by: java.lang.IncompatibleClassChangeError: class shadows.placebo.color.GradientColor cannot inherit from final class net.minecraft.network.chat.TextColor`

The crash in this case was caused by placebo? There's no mention of SDLink or craterlib anywhere in that crash

**Comment by Un1q32** [comment]
Removing sdlink makes it not crash

**Comment by Un1q32** [comment]
I didn't have craterlib installed 💀

**Comment by hypherionmc** [comment]
Ah okay. Confusing crash report from forge there then.

I was going to say, that sdlink by itself shouldn't cause any crashes like this, since it contains 0 minecraft code, so the crash would've been caused by CraterLib. If that was the case, removing sdlink alone would not have solved the issue.

Was about to spin up a test server to see if that was the case, but you beat me to it lol
