### ISSUE TITLE
[BUG] Discord Integration crashes when User logs in on minecraft

### ISSUE THREAD

**Issue by drakknightmc** [hypherionmc/sdlink#21]
The discord integration crashes my minecraft server when a user logs in with the following error.
```---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/2/22, 6:34 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.PlayerEvent$PlayerLoggedInEvent.getPlayer()'
	at me.hypherionmc.sdlink.ForgeEventHandler.playerJoinEvent(ForgeEventHandler.java:77) ~[SimpleDiscordLink-forge-1.19-1.4.0.jar%23107!/:1.4.0] {re:classloading}
	at me.hypherionmc.sdlink.__ForgeEventHandler_playerJoinEvent_PlayerLoggedInEvent.invoke(.dynamic) ~[SimpleDiscordLink-forge-1.19-1.4.0.jar%23107!/:1.4.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2350!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2350!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2350!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:727) ~[forge-1.19-41.1.0-universal.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:243) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:147) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:134) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:78) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:240) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[server-1.19-20220607.102129-srg.jar%23110!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 4.18.0-372.13.1.el8_6.x86_64
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 882341248 bytes (841 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 81825.75
	Virtual memory used (MB): 77573.88
	Swap memory total (MB): 17407.99
	Swap memory used (MB): 562.25
	JVM Flags: 20 total; -Xmx2048M -Xms1331M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Server Running: true
	Player Count: 1 / 1337; [ServerPlayer['Bone_es'/75, l='ServerLevel[world_1665072917]', x=-2750.70, y=80.00, z=-708.03]]
	Data Packs: vanilla, mod:repurposed_structures, mod:dungeoncrawl, mod:awesomedungeonnether, mod:awesomedungeonend, mod:additionalstructures, mod:libraryferret, mod:forge, mod:castle_dungeons, mod:structory, mod:dungeonnowloading, mod:awesomedungeon, mod:dungeons_arise, mod:awesomedungeonocean, file/afk display v1.1.3.zip, file/armored elytra v1.0.6.zip, file/coordinates hud v1.2.3.zip, file/double shulker shells v1.3.3.zip, file/durability ping v1.1.3.zip, file/fast leaf decay v2.0.6.zip, file/homes v1.5.4.zip, file/larger phantoms v1.2.4.zip, file/more mob heads v2.10.1.zip, file/multiplayer sleep v2.6.3.zip, file/real time clock v1.1.3.zip, file/spawn v2.3.3.zip, file/tag v2.1.3.zip, file/tpa v2.3.3.zip, file/track raw statistics v1.5.3.zip, file/villager death messages v1.2.4.zip, file/wandering trades v1.6.0.zip, mod:lapisreserve (incompatible), file/custom villager shops v1.2.3.zip, file/[1.19] Key DP by CMD-Golem v3.4.zip, file/graves v2.8.6.zip, mod:sdlink (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: NOSIGNATURE
		lapisreserve-1.0.8F.jar                           |lapisreserve                  |lapisreserve                  |1.0.8F              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-6.3.11.19.2.jar       |Repurposed Structures         |repurposed_structures         |6.3.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |DONE      |Manifest: NOSIGNATURE
		awesomedungeonnether-forge-1.19-3.0.0.jar         |Awesome dungeon nether        |awesomedungeonnether          |3.0.0               |DONE      |Manifest: NOSIGNATURE
		awesomedungeonend-forge-1.19-3.0.0.jar            |Awesome dungeon the end       |awesomedungeonend             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Rexs-AdditionalStructures-1.19.x-v.4.0.2.jar      |Additional Structures         |additionalstructures          |4.0.2               |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.19-3.0.0.jar                |Library ferret                |libraryferret                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		castle_dungeons-3.3-1.19-forge.jar                |Castle Dungeons               |castle_dungeons               |3.3                 |DONE      |Manifest: NOSIGNATURE
		SimpleDiscordLink-forge-1.19-1.4.0.jar            |Simple Discord Link           |sdlink                        |1.4.0               |DONE      |Manifest: NOSIGNATURE
		Structory-1.19-1.2.jar                            |Structory                     |structory                     |1.0.1               |DONE      |Manifest: NOSIGNATURE
		dungeon-now-loading-17.1-v1.19.jar                |Dungeon Now Loading           |dungeonnowloading             |1.19-17.1           |DONE      |Manifest: NOSIGNATURE
		awesomedungeon-forge-1.19-3.0.0.jar               |Awesome dungeon               |awesomedungeon                |3.0.0               |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.19-2.1.51-beta.jar                |When Dungeons Arise           |dungeons_arise                |2.1.51              |DONE      |Manifest: NOSIGNATURE
		awesomedungeonocean-forge-1.19-3.0.1.jar          |Awesome dungeon edition ocean |awesomedungeonocean           |3.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 83f2849b-387c-4f8e-b6af-772b8de03912
	FML: 41.1
	Forge: net.minecraftforge:41.1.0```

**Comment by hypherionmc** [comment]
Hi. Sorry for the late reply. Was at the hospital all day.

You're trying to use a 1.19.1/2 version on 1.19. The last released update for 1.19 was 1.4.0.

Due to code changes in 1.19.1/2 (from minecraft's side), it's not backward compatible, and once we update from 1.19 to 1.19.1 or above, we basically overwrite all the code for 1.19, which is why no further updates get released.

So you either need to use the 1.4.0 version, or upgrade your minecraft version. If I'm not mistaken, all those mods should be available for 1.19.1+
