### ISSUE TITLE
[BUG] Cannot launch on 1.18.1 forge

### ISSUE THREAD

**Issue by itsdinkd** [hypherionmc/sdlink#3]
Starting server I get this error

(using latest forge modloader, and latest version of your SDLink and Simple RPC)

```java
Exception in thread "main" java.lang.module.ResolutionException: Modules sdlink and simplerpc export package me.hypherionmc.nightconfig.toml to module bettermodsbutton
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

server crashes

**Comment by hypherionmc** [comment]
Well what do you know. My mods conflicting with each other lol. Well not really a conflict. It's using the same library for the config and forge is detecting it as a duplicate. I'll push out a fix later today for this

**Comment by hypherionmc** [comment]
As a workaround for now, you can just remove simple-rpc from your server. It's only needed client side unless you need some of the server side features that not a lot of people really use

**Comment by itsdinkd** [comment]
> As a workaround for now, you can just remove simple-rpc from your server. It's only needed client side unless you need some of the server side features that not a lot of people really use

I do use the Server Entries feature, I love it :) I can hold off until the conflict is fixed, no worries.

**Comment by hypherionmc** [comment]
Hey. Can you confirm if this build fixes the conflict: https://ci.firstdarkdev.xyz/job/Simple%20RPC/job/Forge/job/1.18.x/lastSuccessfulBuild/artifact/build/libs/simple-rpc-1.18-2.7.6d.jar

If so, then I'll release it today

**Comment by hypherionmc** [comment]
Release 2.7 of Simple RPC should fix this problem :)
