### ISSUE TITLE
failed to start server

### ISSUE THREAD

**Issue by CodeLory** [hypherionmc/sdlink#60]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'sdlink'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: me.hypherionmc.moonconfig.core.io.ParsingException: Invalid value: TRUE
        at me.hypherionmc.moonconfig.core.io.Utils.parseLong(Utils.java:67) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.ValueParser.parseNumber(ValueParser.java:125) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.ValueParser.parse(ValueParser.java:63) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.ValueParser.parse(ValueParser.java:68) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.TableParser.parseNormal(TableParser.java:58) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.TableParser.parseNormal(TableParser.java:102) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.TomlParser.parse(TomlParser.java:103) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.toml.TomlParser.parse(TomlParser.java:52) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.moonconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlinklib.config.ConfigController.configUpgrade(ConfigController.java:88) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlinklib.config.ConfigController.initConfig(ConfigController.java:67) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlinklib.config.ConfigController.<init>(ConfigController.java:54) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlinklib.discord.BotController.<init>(BotController.java:103) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlink.server.ServerEvents.<init>(ServerEvents.java:64) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlink.server.ServerEvents.getInstance(ServerEvents.java:50) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at me.hypherionmc.sdlink.SDLinkFabric.onInitializeServer(SDLinkFabric.java:16) ~[SimpleDiscordLink-fabric-1.19.3-2.2.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more

**Comment by hypherionmc** [comment]
Replied to you on discord, but in-case you didn't see it, you have an error in the config. Somewhere you placed `TRUE` that is expecting a LONG value (1234567).

**Comment by hypherionmc** [comment]
Issue resolved on discord. Config formatting issues
