### ISSUE TITLE
[BUG] usage of System.out/err.print

### ISSUE THREAD

**Issue by devzme** [hypherionmc/sdlink#7]
**Describe the bug**
When i try to use the status command shows error:
[14:08:54 ERROR]: [STDERR] [pool-12-thread-3] ERROR JDA - One of the EventListeners had an uncaught exception
[14:08:54 WARN]: Nag author(s): '[HypherionMC]' of 'sdlink' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
and more.

**Expected behavior**
[14:08:54 ERROR]: [STDERR] [pool-12-thread-3] ERROR JDA - One of the EventListeners had an uncaught exception
[14:08:54 WARN]: Nag author(s): '[HypherionMC]' of 'sdlink' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:08:54 WARN]: java.lang.UnsatisfiedLinkError: 'java.lang.String shadow.sun.jna.Native.getNativeVersion()'
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Native.getNativeVersion(Native Method)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Native.<clinit>(Native.java:197)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Structure.setAlignType(Structure.java:291)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Structure.<init>(Structure.java:208)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Structure.<init>(Structure.java:204)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Structure.<init>(Structure.java:191)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.Structure.<init>(Structure.java:183)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1973)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.sun.jna.platform.win32.VersionHelpers.IsWindows7OrGreater(VersionHelpers.java:154)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:154)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:61)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.util.Memoizer$1.get(Memoizer.java:87)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//shadow.oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//me.hypherionmc.sdlinklib.discord.commands.ServerStatusCommand.execute(ServerStatusCommand.java:34)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//com.jagrosh.jdautilities.command.Command.run(Command.java:357)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//com.jagrosh.jdautilities.command.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:648)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//com.jagrosh.jdautilities.command.impl.CommandClientImpl.onEvent(CommandClientImpl.java:535)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[14:08:54 WARN]: 	at SimpleDiscordLink-Spigot-1.1.jar//me.hypherionmc.sdlinklib.discord.BotEngine$ThreadedEventManager.lambda$handle$0(BotEngine.java:107)
[14:08:54 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[14:08:54 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:08:54 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:08:54 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:08:54 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Screenshots**

**Versions (Please give exact numbers, not LATEST!):**
 - Mod Version: SDLink Spigot/Bukkit/Paper 1.1
 - Mod Loader (Put an x inbetween [])
   - [] Forge
   - [] Fabric
   - [x] Spigot etc
 - Mod Loader Version: PaperMC#200(1.18.1)
 - Minecraft Version: 1.18.1

**Additional context or crash logs**
[](https://dev.bukkit.org/projects/simple-discord-link-bot-forge-fabric-spigot/files/3568820/download)[SDLink Spigot/Bukkit/Paper 1.1](https://dev.bukkit.org/projects/simple-discord-link-bot-forge-fabric-spigot/files/3568820)

**Comment by hypherionmc** [comment]
Hmmm. Looks like something with the system info library is broken.

As for the System.print errors, I can't do anything about that. The discord bot library uses that as their logging system, and since it's a pre-made library, I cannot make changes to it

**Comment by devzme** [comment]
OK. Thanks for review.
