### ISSUE TITLE
"Could not initialize bot. Could not load config or your Bot Token is missing. Bot will be disabled" even though i am 110% sure the token is correct.

### ISSUE THREAD

**Issue by catlovelia** [hypherionmc/sdlink#91]
ive tried again and again, making new bots, changing channels, nothing is working and ive been trying for 5 hours. i give up. please help me.

**Comment by hypherionmc** [comment]
What version are you on, what mc version are you using, what is the full error from the log. 

I can't help without that information, as I have no way of knowing what's going on, on your server

**Comment by catlovelia** [comment]
[14:55:22] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.22
[14:55:22] [ForkJoinPool-1-worker-3/WARN]: Mod letmedespawn uses the version fabric-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:55:22] [main/WARN]: Warnings were found!
 - Mod 'BetterSleeping Core' (bettersleeping-core) 0.6.1 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Dynamic Lights' (dynamiclights) 1.7+mod recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Dynamic Lights' (dynamiclights) 1.7+mod recommends any version of modmenu-badges-lib, which is missing!
	 - You should install any version of modmenu-badges-lib for the optimal experience.
 - Mod 'Dynamic Lights' (dynamiclights) 1.7+mod recommends any version of midnightlib, which is missing!
	 - You should install any version of midnightlib for the optimal experience.
 - Mod 'SleepWarp' (sleepwarp) 2.0.0+1.19.2 recommends version 4.2.0-beta.2 of modmenu, which is missing!
	 - You should install version 4.2.0-beta.2 of modmenu for the optimal experience.
**[14:55:22] [main/INFO]: Loading 146 mods:
	- adorn 3.9.1+1.19.2
	- anvilrestoration 2.0
	- automaticdoors 4.4
	- balm-fabric 4.5.7
	- bettersleeping 0.6.1+1.19
	   |-- bettersleeping-core 0.6.1
	   \-- org_apache_commons_commons-text 1.9
	- bitsandchisels 2.7.0
	   \-- stacc 1.3.4
	- bottleyourxp 3.1
	- carryon 2.1.0.20
	- chimes 2.0.1
	- chunky 1.3.38
	- cloth-config 8.3.103
	   \-- cloth-basic-math 0.6.1
	- collective 6.66
	- conduitspreventdrowned 3.2
	- connectiblechains 2.1.4+1.19.2
	- convenient-mobgriefing 2.0.2
	- creeperoverhaul 2.0.9
	- crittersandcompanions 1.19.2-2.0.1
	- croptopia 2.2.2
	   |-- com_typesafe_config 1.4.1
	   |-- io_leangen_geantyref_geantyref 1.3.11
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- cryingportals 2.3
	- day_dream 1.0.5
	- despawningeggshatch 4.1
	- doubledoors 5.0
	- dynamiclights 1.7+mod
	- extrakeybinds 0.5.0+1.17-1.19.4
	- fabric-api 0.76.1+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.10.8+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.22
	- fabsit 1.5.3+1.19
	- ferritecore 5.0.3
	- fishonaleash 1.19-1.0.0
	- fishontheline 3.0
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- gottagofast 1.0.2
	- healingcampfire 5.1
	- java 20
	- justmobheads 7.3
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- ksyxis 1.1
	- letmedespawn fabric-1.0.2
	- lithium 0.11.1
	- logprot 1.19-2.0
	- memoryleakfix 1.1.1
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- minecraft 1.19.2
	- moborigins 1.10.0
	- nametagtweaks 3.0
	- naturallychargedcreepers 3.2
	- nohostilesaroundcampfire 5.4
	- origins 1.7.1
	   |-- apoli 2.6.1
	   |    |-- additionalentityattributes 1.0.0+1.19
	   |    |-- calio 1.7.0
	   |    |-- cardinal-components-base 5.0.1
	   |    |-- cardinal-components-entity 5.0.1
	   |    \-- playerabilitylib 1.6.0
	   \-- reach-entity-attributes 2.3.0
	- origins-plus-plus 2.1.1
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- pehkui 3.7.8+1.14.4-1.20.1
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- resourcefulconfig 1.0.20
	- respawningshulkers 3.5
	- sdlink 2.2.4
	- server-hats 0.14
	- servercore 1.3.3-1.19.2
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- me_lucko_spark-api 0.1-SNAPSHOT
	   \-- placeholder-api 2.0.0-pre.1+1.19.2
	- servertick 1.7
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- sleepwarp 2.0.0+1.19.2
	- smoothboot 1.19-1.7.1
	- spark 1.10.37
	- starlight 1.1.1+fabric.ae22326
	- vcinteraction 1.19.2-1.0.3
	   \-- polymer 0.2.19+1.19.2
	        |-- packet_tweaker 0.3.0+1.18.2
	        \-- polymer-registry-sync-manipulator 0.0.3+1.19.2
	- voicechat 1.19.2-2.4.19
	   \-- fabric-key-binding-api-v1 1.0.18+9ff28f4095
	- waystones 11.4.1
	- wooltweaks 3.1
	- worldedit 7.2.12+6240-87f4ae1
	- xlpackets 1.19.2-4
	- yet-another-config-lib 2.2.0-for-1.19.2
	- zombiehorsespawn 4.6**
[14:55:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Lia/Desktop/serber/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:55:22] [main/INFO]: Compatibility level set to JAVA_17
[14:55:22] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 4 override(s) found
[14:55:22] [main/INFO]: [ServerCore] Loading...
[14:55:22] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[14:55:22] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[14:55:22] [main/WARN]: Force-enabling mixin 'block.hopper.worldedit_compat.WorldChunkMixin' as rule 'mixin.block.hopper.worldedit_compat' (added by mods [lithium-fabric]) enables it
[14:55:22] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[14:55:22] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
[14:55:23] [main/INFO]: [MemoryLeakFix] Will be applying 2 memory leak fixes!
[14:55:23] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [entityMemoriesLeak, biomeTemperatureLeak]
[14:55:23] [main/INFO]: Smooth Boot config initialized
[14:55:25] [main/INFO]: Building unoptimized datafixer
[14:55:26] [main/INFO]: apoli.mixins.json:ItemSlotArgumentTypeAccessor from mod apoli->@Accessor[FIELD_GETTER]::getSlotNamesToSlotCommandId()Ljava/util/Map; should be static as its target is
[14:55:27] [main/INFO]: Apoli 2.6.1 has initialized. Ready to power up your game!
[14:55:27] [main/INFO]: Loading Collective version 6.66.
[14:55:27] [main/INFO]: Initialized entity types.
[14:55:27] [main/ERROR]: No data fixer registered for jungle_creeper
[14:55:27] [main/ERROR]: No data fixer registered for bamboo_creeper
[14:55:27] [main/ERROR]: No data fixer registered for desert_creeper
[14:55:27] [main/ERROR]: No data fixer registered for badlands_creeper
[14:55:27] [main/ERROR]: No data fixer registered for hills_creeper
[14:55:27] [main/ERROR]: No data fixer registered for savannah_creeper
[14:55:27] [main/ERROR]: No data fixer registered for mushroom_creeper
[14:55:27] [main/ERROR]: No data fixer registered for swamp_creeper
[14:55:27] [main/ERROR]: No data fixer registered for dripstone_creeper
[14:55:27] [main/ERROR]: No data fixer registered for cave_creeper
[14:55:27] [main/ERROR]: No data fixer registered for dark_oak_creeper
[14:55:27] [main/ERROR]: No data fixer registered for spruce_creeper
[14:55:27] [main/ERROR]: No data fixer registered for beach_creeper
[14:55:27] [main/ERROR]: No data fixer registered for snowy_creeper
[14:55:27] [main/ERROR]: No data fixer registered for ocean_creeper
[14:55:28] [main/INFO]: [Dynamic Lights] Loaded Dynamic Lights by Tschipcraft successfully!
[14:55:28] [main/INFO]: FabSit loaded
[14:55:28] [main/INFO]: [STDOUT]: Fish on a Leash! has been successfully initialized.
[14:55:28] [main/INFO]: GottaGoFast Fabric by PixelAgent007 loaded sucessfully!
[14:55:28] [main/INFO]: Compression will use Java, encryption will use Java
[14:55:28] [main/WARN]: Ksyxis will speedup your world loading. :P
[14:55:28] [main/WARN]: BUT IT MAY CAUSE ISSUES (INCLUDING COMPAT). DON'T ASK OTHER MODS' AUTHORS FOR COMPAT!
[14:55:28] [main/INFO]: Shields up!
[14:55:28] [main/INFO]: Mob Origins version 1.10.0 is loaded!
[14:55:28] [main/INFO]: Origins 1.7.1 is initializing. Have fun!
[14:55:28] [main/INFO]: glisco: I like this approach, cause it's stateless. And stateless approaches are always good since state management is pain - BasiqueEvangelist: I like french bread
[14:55:28] [main/INFO]: Compatibility version 17
[14:55:28] [main/INFO]: Loading plugins
[14:55:28] [main/INFO]: Loaded 1 plugin(s)
[14:55:28] [main/INFO]: Initializing plugins
[14:55:28] [main/INFO]: Initialized 1 plugin(s)
[14:55:28] [main/INFO]: Registering events for vcinteraction
[14:55:28] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@7958b881]
[14:55:28] [main/INFO]: WorldEdit for Fabric (version 7.2.12+6240-87f4ae1) is loaded
[14:55:28] [main/INFO]: Krypton is now accelerating your Minecraft server's networking stack 🚀
_[14:55:28] [main/ERROR]: Could not initialize bot. Could not load config or your Bot Token is missing. Bot will be disabled_
[14:55:28] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:55:29] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[14:55:29] [main/INFO]: Registering commands with com.sk89q.worldedit.fabric.FabricPlatform
[14:55:30] [main/INFO]: Loaded 8 recipes
[14:55:30] [main/ERROR]: Failed to load function dynamiclights:internal/water/rain_check
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 4: Incorrect argument for command at position 11: ...xecute if <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 4: Incorrect argument for command at position 11: ...xecute if <--[HERE]
	at net.minecraft.class_2158.method_9195(class_2158.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_5349.method_29451(class_5349.java:85) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[14:55:30] [main/INFO]: Loaded 1872 advancements
[14:55:30] [main/INFO]: Finished loading powers from data files. Registry contains 2624 powers.
[14:55:30] [main/INFO]: Finished loading origins from data files. Registry contains 140 origins.
[14:55:30] [main/INFO]: Trying to read layer file: origins:origin
[14:55:30] [main/INFO]: Trying to read layer file: origins:origin
[14:55:30] [main/INFO]: Trying to read layer file: origins:origin
[14:55:30] [main/INFO]: Finished loading origin layers from data files. Read 1 layers.
[14:55:31] [main/INFO]: Applied 408 biome modifications to 63 of 63 new biomes in 12.34 ms
[14:55:31] [Server thread/INFO]: [ServerHats]: Successfully added ability to equip all items
[14:55:31] [Server thread/INFO]: Starting background profiler...
[14:55:31] [Server thread/INFO]: The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[14:55:31] [Server thread/INFO]: **Starting minecraft server version 1.19.2**
[14:55:31] [Server thread/INFO]: Loading properties
[14:55:31] [Server thread/INFO]: Default game type: SURVIVAL
[14:55:31] [Server thread/INFO]: Generating keypair
[14:55:31] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:55:31] [Server thread/INFO]: Using default channel type
[14:55:31] [Server thread/INFO]: Preparing level "world"
[14:55:37] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:55:37] [Server thread/INFO]: Not the long loadi-
[14:55:37] [Server thread/INFO]: Time elapsed: 286 ms
[14:55:37] [Server thread/INFO]: Done (5.626s)! For help, type "help"
[14:55:37] [VoiceChatServerThread/INFO]: Voice chat server started at port 24454
[14:55:43] [User Authenticator #1/INFO]: UUID of player catlovelia is f5683e35-cb0b-40b9-bc48-6dab8084c3fe
[14:55:44] [Server thread/INFO]: catlovelia[/127.64.167.1:57305] logged in with entity id 914 at (-62.814249386461206, 61.47842620707041, -80.36036179535905)
[14:55:44] [Server thread/INFO]: Using Fabric Permissions API
[14:55:44] [Server thread/INFO]: catlovelia joined the game
[14:55:44] [Server thread/INFO]: Received secret request of catlovelia (17)
[14:55:44] [Server thread/INFO]: Sent secret to catlovelia
[14:55:51] [Server thread/INFO]: <catlovelia> test
[15:11:18] [Server thread/INFO]: catlovelia lost connection: Disconnected
[15:11:18] [Server thread/INFO]: catlovelia left the game
[15:11:18] [Server thread/INFO]: Disconnecting client catlovelia
[17:13:49] [Server thread/INFO]: Stopping server
[17:13:49] [Server thread/INFO]: Saving players
[17:13:49] [Server thread/INFO]: Saving worlds
[17:13:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:13:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[17:13:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[17:13:49] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:13:49] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:13:49] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:13:49] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by catlovelia** [comment]
Bold is server information, italic is the error
Edit: the bolding didnt seem to work but im sure you can find it

**Comment by hypherionmc** [comment]
Sorry for the late response, your response came through after I went to bed.

Can you share your config file please? Just replace some random characters in your bot token to make it invalid, and if you use webhooks, please remove their urls

**Comment by catlovelia** [comment]
```
#General Mod Config
[general]
	#Should the bot be enabled or not
	enabled = true
	#Should debug logging be enabled? WARNING: THIS CAN SPAM YOUR LOG!
	debugging = false
	#Should the bot be allowed to whitelist/un-whitelist players. Whitelisting needs to be enabled on your server as well
	whitelisting = false
	#Should the bot be allowed to whitelist/un-whitelist players in OFFLINE mode. Whitelisting needs to be enabled on your server as well
	offlinewhitelist = false
	#Automatically link Minecraft and Discord Accounts when a user is whitelisted
	linkedWhitelist = false
	#Should only admins be allowed to whitelist players
	onlyAdminsWhitelist = false
	#If a role ID (or name) is defined here, it will be assigned to players when they are whitelisted
	autoWhitelistRole = ""
	#Modify user nickname when their accounts are linked
	modifyNickname = false
	#If a role ID (or name) is defined here, it will be assigned to players when their MC and Discord accounts are linked
	linkedRole = ""
	#Should the /discord command be enabled in game
	inviteCommandEnabled = false
	#Discord Invite Link used by the in-game invite command
	inviteLink = ""
	#Internal version control. DO NOT TOUCH!
	configVersion = 25

#Config specific to the discord bot
[botConfig]
	#The Token of the Bot to use. KEEP THIS PRIVATE. See https://readme.firstdarkdev.xyz/simple-discord-link/initial-setup/ to find this
	botToken = "nuh uh."
	#How quickly the bot status should update
	activityUpdateInterval = 1
	#If a role ID (or name) is defined here, only members with this role can use Staff Functions. Otherwise, it defaults back to admin/kick perms
	staffRole = ""
	#Should the bot use / commands. NOTE: THIS MAY TAKE UP TO 24 HOURS TO SHOW UP IN YOUR DISCORD
	slashCommands = false
	#The prefix to use for bot commands. Example: ~players. THIS HAS NO EFFECT WHEN USING SLASH COMMANDS
	# - WARNING: TEXT COMMANDS HAVE BEEN DEPRECATED, USE SLASH COMMANDS INSTEAD!!
	botPrefix = "~"
	#Do not add Playing. A status to display on the bot. You can use %players% and %maxplayers% to show the number of players on the server
	botStatus = "Minecraft"
	#The type of the status displayed on the bot. Valid entries are: PLAYING, STREAMING, WATCHING, LISTENING
	botStatusType = "PLAYING"
	#The URL that will be used when the "botStatusType" is set to "STREAMING", required to display as "streaming".
	botStatusStreamingURL = "https://twitch.tv/twitch"
	#Should the bot update the topic of your chat channel automatically
	doTopicUpdates = true
	#A topic for the Chat Relay channel. You can use %player%, %maxplayers%, %uptime% or just leave it empty.
	channelTopic = "Playing Minecraft with %players%/%maxplayers% people | Uptime: %uptime%"

#Config relating to the discord channels to use with the mod
[channels]
	#The ID of the channel to post in and relay messages from. This is still needed, even in webhook mode
	chatChannelID = nope.
	#If this ID is set, event messages will be posted in this channel instead of the chat channel
	eventsChannelID = 0
	#If this ID is set, console messages sent after the bot started will be relayed here, and you can execute minecraft commands here
	consoleChannelID = still not happenin

#Webhook Config
[webhooks]
	#Should webhook messages be used
	enabled = false
	#The URL of the channel webhook to use for Chat Messages
	chatWebhook = ""
	#The URL of the channel webhook to use for Server Messages
	eventsWebhook = ""
	#The URL of the channel webhook to use for Console Messages
	consoleWebhook = ""
	#A DIRECT link to an image to use as the avatar for server messages. Also used for embeds
	serverAvatar = ""
	#The name to display for Server messages when using Webhooks
	serverName = "Minecraft Server"

#Chat Config
[chat]
	#The type of image to use as the player icon in messages. Valid entries are: AVATAR, HEAD, BODY, COMBO
	playerAvatarType = "HEAD"
	#Prefix to add to Minecraft when a message is relayed from Discord. Supports MC formatting. Use %user% for the Discord Username
	mcPrefix = "§e[Discord]§r %user%: "
	#Should messages from bots be relayed
	ignoreBots = true
	#Should SERVER STARTING messages be shown
	serverStarting = true
	#Should SERVER STARTED messages be shown
	serverStarted = true
	#Should SERVER STOPPING messages be shown
	serverStopping = true
	#Should SERVER STOPPED messages be shown
	serverStopped = true
	#Should the chat be relayed
	playerMessages = true
	#Should Join and Leave messages be posted
	joinAndLeaveMessages = true
	#Should Advancement messages be posted
	advancementMessages = true
	#Should Death Announcements be posted
	deathMessages = true
	#Should Messages from the /say command be posted
	sendSayCommand = true
	#Should commands be posted to discord
	broadcastCommands = true
	#Commands that should not be broadcasted to discord
	ignoredCommands = ["particle", "login"]

#Change the contents of certain event messages
[messages]
	#Convert Discord to MC, and MC to Discord Formatting
	formatting = true
	#Should console messages be sent to the Console Channel
	sendConsoleMessages = true
	#Server Starting Message
	serverStarting = "*Server is starting...*"
	#Server Started Message
	serverStarted = "*Server has started. Enjoy!*"
	#Server Stopping Message
	serverStopping = "*Server is stopping...*"
	#Server Stopped Message
	serverStopped = "*Server has stopped...*"
	#Player Joined Message. Use %player% to display the player name
	playerJoined = "*%player% has joined the server!*"
	#Player Left Message. Use %player% to display the player name
	playerLeft = "*%player% has left the server!*"
	#Achievement Messages. Available variables: %player%, %title%, %description%
	achievements = "*%player% has made the advancement [%title%]: %description%*"
	#Chat Messages. Available variables: %player%, %message%
	chat = "%message%"
	#Command Messages. Available variables: %player%, %command%
	commands = "%player% **executed command: %command%**"
	#Should messages sent with TellRaw be sent to discord as a chat? (Experimental)
	relayTellRaw = true
	#Should the entire command executed be relayed to discord, or only the name of the command
	relayFullCommands = false
	#The message to show when someone uses /discord command. You can use %inviteurl%
	inviteMessage = "Hey, check out our discord server here -> %inviteurl%"

#Change in which channel messages appear
[messageDestinations]

	#Control where CHAT messages are delivered
	[messageDestinations.chat]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where START/STOP messages are delivered
	[messageDestinations.startStop]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where JOIN/LEAVE messages are delivered
	[messageDestinations.joinLeave]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where ADVANCEMENT messages are delivered
	[messageDestinations.advancements]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where DEATH messages are delivered
	[messageDestinations.death]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where COMMAND messages are delivered
	[messageDestinations.commands]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

#Enable or Disable certain bot commands
[botCommands]
	#Allow members to link their MC and Discord accounts
	accountLinking = true
	#Enable/Disable the Player List command
	allowPlayerList = true
	#Enable/Disable the Server Status command
	allowServerStatus = true

#Execute Minecraft commands in Discord
[linkedCommands]
	#Should linked commands be enabled
	enabled = false
	#Commands to be linked
	commands = []
```

**Comment by hypherionmc** [comment]
Reason I asked to keep the token intact, but change some random numbers, is to see if you were using the correct one.

If your token doesn't look like this `OTA1NDEyMzEyOTUxODQ5MDEw.Gr1ie6.72gPskqxrfLcYW3xqTSc9dO6cLSwszXYYmQgOw`, it's wrong. 

If it looks like this: `905412312951849010` -> Wrong
If it looks like this: `93384c194fbd366c57df2d3531f4fcc8982696748daf3a36204f1b2bde606895` -> Wrong

(Notice, none of these are real values)

It has to match the format shown above. It's found here:
![image](https://github.com/hypherionmc/sdlink/assets/63595580/69770a80-1f4f-422c-b807-af31c8a4e519)

**Comment by catlovelia** [comment]
it has both numbers and letters, thats for certain
I am, once again, 110% sure the bot token is correct

**Comment by hypherionmc** [comment]
To this day, I still don't know what caused this, nor has anyone else reported this happening again. 

The newer versions should have additional logging now for config loading errors that could cause this, instead of just saying the token is invalid or missing.

I'm going to go ahead and close this for now (just to clean up our active issues a bit). If you are still a user of this mod, or ever plan on doing so again (which I don't blame you if you won't) and this issue occurs again, please let us know

**Comment by catlovelia** [comment]
Hate to bother, but i tried it again, configured with https://editor.firstdark.dev , and it worked like a charm!

**Comment by hypherionmc** [comment]
How did you originally edit it? A text editor on Windows, or one included with your server hosting?
